// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BrunchLogo: typeof import('./src/components/icons/BrunchLogo.vue')['default']
    BrunchLogoWhite: typeof import('./src/components/icons/BrunchLogoWhite.vue')['default']
    'Carbon:arrowUp': typeof import('~icons/carbon/arrow-up')['default']
    'Carbon:close': typeof import('~icons/carbon/close')['default']
    'Carbon:logo': typeof import('~icons/carbon/logo')['default']
    'Carbon:menu': typeof import('~icons/carbon/menu')['default']
    DarkToggleButton: typeof import('./src/components/slides/DarkToggleButton.vue')['default']
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GitHubLink: typeof import('./src/components/GitHubLink.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Marker: typeof import('./src/components/slides/Marker.vue')['default']
    MarkerCore: typeof import('./src/components/slides/MarkerCore.vue')['default']
    MarkerPattern: typeof import('./src/components/slides/MarkerPattern.vue')['default']
    MarkerTips: typeof import('./src/components/slides/MarkerTips.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    ReadProgressBar: typeof import('./src/components/ReadProgressBar.vue')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    'SimpleLineIcons:socialYoutube': typeof import('~icons/simple-line-icons/social-youtube')['default']
    Slidev: typeof import('./src/components/icons/Slidev.vue')['default']
    SolidLogo: typeof import('./src/components/icons/SolidLogo.vue')['default']
    StarsRanking: typeof import('./src/components/StarsRanking.vue')['default']
    TailwindNavBar: typeof import('./src/components/TailwindNavBar.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    ViteLogo: typeof import('./src/components/icons/ViteLogo.vue')['default']
    VueDemi: typeof import('./src/components/icons/VueDemi.vue')['default']
    VueReactivity: typeof import('./src/components/icons/VueReactivity.vue')['default']
    VueUse: typeof import('./src/components/icons/VueUse.vue')['default']
    VueUseFn: typeof import('./src/components/slides/VueUseFn.vue')['default']
  }
}

export { }
